# Generated by Django 4.2.23 on 2025-07-13 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='address',
        ),
    ]
