# Generated by Django 4.2.23 on 2025-07-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_homepage_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cash_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_state',
            field=models.CharField(blank=True, choices=[('1', 'Garaşylýar'), ('2', 'Tassyklandy'), ('3', 'Eltip berildi'), ('4', 'Yza gaýtaryldy'), ('5', 'Ýatyryldy')], default='1', max_length=10, null=True),
        ),
    ]
