# Generated by Django 4.2.23 on 2025-07-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_orderitem_cash_balance_alter_order_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productwarehouse',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
