# Generated by Django 4.2.23 on 2025-07-18 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_productwarehouse_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order_fk',
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.orderitem'),
        ),
    ]
